'use client'
import './globals.css'

import { PropsWithChildren } from 'react'
import { lightTheme } from './theme/themes'
import ContextProvider from './context-provider'
import Box from '@mui/material/Box'
import { ThemeProvider, CssBaseline } from '@mui/material'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import { usePathname } from 'next/navigation'

export default function RootLayout({ children }: PropsWithChildren<{}>) {
  const router = usePathname()

  const showHeader =
    router === '/signin' || router === '/signup' || router === '/email' || router === '/password'
      ? false
      : true
  return (
    <html lang='en'>
      <head>
        <title>All Star Driving School Ltd</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <ThemeProvider theme={lightTheme}>
        <ContextProvider>
          <body>
            <CssBaseline />
            {showHeader && <Header />}
            <Box sx={{ display: 'flex' }}>
              <CssBaseline />
              {showHeader && <Sidebar />}
              {/* {<Header/>} */}
              <Box component='main' sx={{ flexGrow: 1, backgroundColor: '#222222' }}>
                {children}
              </Box>
            </Box>
          </body>
        </ContextProvider>
      </ThemeProvider>
    </html>
  )
}
